### ISSUE TITLE
Installing ponyd fails due to pybonjour download failure

### ISSUE THREAD

**Issue by mark-anders** [square/PonyDebugger#126] opened 2014-09-04 21:11 UTC
I'm using OS X 10.10 with the latest tools installed.  When using the curl method to install ponyd and removing the -k parameter as per #125, I get the following error:
```
Downloading/unpacking pybonjour (from ponydebugger)
  Could not find any downloads that satisfy the requirement pybonjour (from ponydebugger)
  Some externally hosted files were ignored (use --allow-external pybonjour to allow).
Cleaning up...
No distributions at all found for pybonjour (from ponydebugger)
```
I've checked the file ~/Library/PonyDebugger/src/ponydebugger/scripts/_bootstrap_contents.py and it contains '--allow-external'.  

Any way to work around it?

**Comment by zettlunic** [comment] 2015-04-13 10:44
Thank you very much @mark-anders!

**Comment by zkirill** [comment] 2015-05-05 21:39
Thank you @mark-anders!

**Comment by codesourse** [comment] 2015-05-25 08:54
when i use "pip install -U -e git+https://github.com/square/PonyDebugger.git#egg=ponydebugger --allow-external pybonjour --allow-unverified pybonjour"
i meet following problem ,anyone can help me.

Collecting pybonjour (from ponydebugger)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(65, 'No route to host'))': /p/pybonjour/
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(65, 'No route to host'))': /p/pybonjour/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(65, 'No route to host'))': /p/pybonjour/

**Comment by FromPointer** [comment] 2015-06-19 02:50
@codesourse,  i have the same problem. how to solve it?

**Comment by ybbaigo** [comment] 2015-09-15 08:28
+1 for the same issue as @codesourse

**Comment by iamdaiyuan** [comment] 2015-09-24 11:01
thank you.

**Comment by codesourse** [comment] 2015-09-24 11:03
use this log  https://github.com/fpillet/NSLogger

**Comment by Kirow** [comment] 2015-10-16 10:59
Thank you @mark-anders!

**Comment by zziking** [comment] 2015-12-01 11:45
@codesourse @ybbaigo is because of your host can not reach the pybonjour code in google's server:  https://code.google.com/p/pybonjour/downloads/list?can=1, you can use --proxy option for pip install, such as : 
pip install -U -e git+https://github.com/square/PonyDebugger.git#egg=ponydebugger --allow-external pybonjour --allow-unverified pybonjour --proxy="the proxy can reach code.google.com"

**Comment by grioja** [comment] 2016-01-20 21:46
Is there an update here? Pretty much any installation on Mac simply fails.

**Comment by Derimagia** [comment] 2016-01-30 23:39
Pretty sure this is related to / a duplicate of Bug #100

**Comment by justinseanmartin** [comment] 2016-03-13 02:28
I believe this should be addressed by #186. If not, please use issue #100 to track this.

**Closed** 2016-03-13 02:29 UTC
