### ISSUE TITLE
Could not find a version that satisfies the requirement pybonjour==1.1.1 

### ISSUE THREAD

**Issue by xiongzenghuidegithub** [square/PonyDebugger#187] opened 2016-03-21 11:40 UTC
Could not find a version that satisfies the requirement pybonjour==1.1.1 (from ponyd) (from versions: )
No matching distribution found for pybonjour==1.1.1 (from ponyd)

**Comment by justinseanmartin** [comment] 2016-03-21 15:16
Dupe of #100. You should be unblocked by:

```
git clone git@github.com:square/PonyDebugger.git
cd PonyDebugger
python setup.py install
```

Please confirm this works for you. I've logged #189 to track fixing the install script and/or instructions.

**Closed by justinseanmartin** 2016-03-21 15:16 UTC

**Comment by xiongzenghuidegithub** [comment] 2016-03-22 04:15
thanks~~~
