### ISSUE TITLE
No matching distribution found for pybonjour (from ponydebugger)

### ISSUE THREAD

**Issue by i-phil** [square/PonyDebugger#174] opened 2015-10-21 17:06 UTC
i use this command:
sudo pip install -U -e git+https://github.com/square/PonyDebugger.git#egg=ponydebugger --allow-external pybonjour --allow-unverified pybonjour

there is log:
Collecting pybonjour (from ponydebugger)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(65, 'No route to host'))': /p/pybonjour/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(65, 'No route to host'))': /p/pybonjour/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(65, 'No route to host'))': /p/pybonjour/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(65, 'No route to host'))': /p/pybonjour/downloads/list?can=1
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(65, 'No route to host'))': /p/pybonjour/downloads/list?can=1
  Could not find a version that satisfies the requirement pybonjour (from ponydebugger) (from versions: )
No matching distribution found for pybonjour (from ponydebugger)

has anyone can help me?

**Comment by dstd** [comment] 2015-12-25 21:10
It looks like `pybonjour` repo is gone. I've solved this issue by preinstallation of pybonjour from one of the mirrors of its repositories at github:
```
pip install -e git+https://github.com/Eichhoernchen/pybonjour.git#egg=pybonjour
```
Then installation command specified in README of PonyDebugger works just fine.

**Comment by gruhls508** [comment] 2016-01-17 18:34
aaaand @dstd is my hero today. Thank you sir.

**Comment by Derimagia** [comment] 2016-01-30 23:39
Pretty sure this is related to / a duplicate of Bug #100

**Comment by justinseanmartin** [comment] 2016-03-13 02:32
I believe this should be addressed by #186. If not, please use issue #100 to track this.

**Closed by justinseanmartin** 2016-03-13 02:32 UTC

**Comment by i-phil** [comment] 2016-03-13 03:33
thx

**Comment by Jonyx4** [comment] 2017-01-10 20:45
thanks @dstd ! that worked for me!
