### ISSUE TITLE
 Could not find a version that satisfies the requirement pybonjour==1.1.1 (from ponyd) (from versions: ) No matching distribution found for pybonjour==1.1.1 (from ponyd)

### ISSUE THREAD

**Issue by sandeepgs1984** [square/PonyDebugger#188] opened 2016-03-21 12:55 UTC
getting this error while installing:

"Could not find a version that satisfies the requirement pybonjour==1.1.1 (from ponyd) (from versions: )
No matching distribution found for pybonjour==1.1.1 (from ponyd)"

please look into this....

My OSX version: OS X El Capitan 10.11.2 (15C50)

**Comment by justinseanmartin** [comment] 2016-03-21 15:15
Dupe of #100. You should be unblocked by:

```
git clone git@github.com:square/PonyDebugger.git
cd PonyDebugger
python setup.py install
```

Please confirm this works for you. I've logged #189 to track fixing the install script and/or instructions.

**Closed by justinseanmartin** 2016-03-21 15:15 UTC

**Comment by sandeepgs1984** [comment] 2016-03-22 09:45
Getting following error while executing your lines:

Cbz-admins-MacBook-Pro:Source sandeep.gs$ git clone git@github.com:square/PonyDebugger.git
Cloning into 'PonyDebugger'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by justinseanmartin** [comment] 2016-03-22 16:37
This is unrelated to PonyDebugger itself, but the issue is that you can't clone with SSH if you don't have SSH keys set up for GitHub (https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/). Alternatively, you can change the clone URL to the HTTPS version and it will prompt for your username and password.
